// SPDX-FileCopyrightText: 2022 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2023 Artjom <artjombebenin@gmail.com>
// SPDX-FileCopyrightText: 2023 Artur <thearturzh@gmail.com>
// SPDX-FileCopyrightText: 2023 faint <46868845+ficcialfaint@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 nikthechampiongr <32041239+nikthechampiongr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes; // Pirate: records photos

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralStationRecordConsoleWindow : DefaultWindow
{
    #region Pirate: records photos
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<uint>? OnDeleteRecord;
    public Action<string>? OnCreateRecord;
    public Action<string, string, string, int, Robust.Shared.Enums.Gender>? OnIdentityInfoChanged;
    public Action<string, string>? OnForensicsInfoChanged;
    private uint? _selectedKey;
    private uint _maxLength;
    private bool _canManageRecords;
    private bool _deleteConfirmationPending;
    private uint? _deleteConfirmationKey;
    #endregion

    private bool _isPopulating;
    private StationRecordFilterType _currentFilterType;

    public GeneralStationRecordConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Pirate: records photos

        _currentFilterType = StationRecordFilterType.Name;

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            StationRecordsFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            #region Pirate: records photos
            if (_isPopulating)
                return;

            if (!HasSelectedRecord()) // Pirate: avoid spurious null deselection events
                OnKeySelected?.Invoke(null);
            #endregion
        };

        StationRecordsFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType) eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(StationRecordsFiltersValue.Text); // Pirate: records photos
                ClearCreateRecordValidation(); // Pirate: add-record validation
                UpdateRecordActionButtons(); // Pirate: add-record validation
            }
        };

        #region Pirate: records photos
        StationRecordsFiltersValue.OnTextEntered += args => FilterListingOfRecords(args.Text);
        StationRecordsFiltersValue.OnTextChanged += _ =>
        {
            ResetDeleteConfirmation();
            ClearCreateRecordValidation(); // Pirate: add-record validation
            UpdateRecordActionButtons();
        };

        AddRecordButton.OnPressed += _ => CreateRecordFromSearch();
        DeleteRecordButton.OnPressed += _ =>
        {
            if (_selectedKey == null)
                return;

            if (_deleteConfirmationPending && _deleteConfirmationKey == _selectedKey)
            {
                ResetDeleteConfirmation();
                OnDeleteRecord?.Invoke(_selectedKey.Value);
                return;
            }

            _deleteConfirmationPending = true;
            _deleteConfirmationKey = _selectedKey;
            UpdateRecordActionButtons();
        };

        UpdateRecordActionButtons();
        #endregion
    }

    public void UpdateState(GeneralStationRecordConsoleState state)
    {
        var previousSelectedKey = _selectedKey; // Pirate: records photos
        _maxLength = state.MaxStringLength; // Pirate: records photos
        _canManageRecords = state.CanDeleteEntries; // Pirate: records photos
        StationRecordsFiltersValue.IsValid = null; // Pirate: add-record sanitization

        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != StationRecordsFiltersValue.Text)
            {
                StationRecordsFiltersValue.Text = state.Filter.Value;
            }
        }

        _selectedKey = state.SelectedKey; // Pirate: records photos
        if (previousSelectedKey != _selectedKey) // Pirate: records photos
            ResetDeleteConfirmation(); // Pirate: records photos

        StationRecordsFilterType.SelectId((int) _currentFilterType); // Pirate: records photos

        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            RecordContainer.Visible = false;
            RecordContainerStatus.Visible = false;
            UpdateRecordActionButtons(); // Pirate: records photos
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        RecordContainer.Visible = true;
        PopulateRecordListing(state.RecordListing, state.SelectedKey); // Pirate: records photos
        UpdateRecordActionButtons(); // Pirate: records photos

        RecordContainerStatus.Visible = state.Record == null;

        if (state.Record != null)
        {
            RecordContainerStatus.Visible = state.SelectedKey == null;
            RecordContainerStatus.Text = state.SelectedKey == null
                ? Loc.GetString("general-station-record-console-no-record-found")
                : Loc.GetString("general-station-record-console-select-record-info");
            PopulateRecordContainer(state.Record); // Pirate: records photos
        }
        else
        {
            RecordContainer.RemoveAllChildren();
        }
    }
    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }
        _isPopulating = false;

        RecordListing.SortItemsByText();
    }

    private void PopulateRecordContainer(GeneralStationRecord record) // Pirate: records photos
    {
        RecordContainer.RemoveAllChildren();
        #region Pirate: records photos
        var newRecord = new GeneralRecord(record, _maxLength, _prototypeManager);
        newRecord.OnIdentityInfoChanged += (species, nationality, employer, age, gender) =>
            OnIdentityInfoChanged?.Invoke(species, nationality, employer, age, gender);
        newRecord.OnForensicsInfoChanged += (fingerprint, dna) =>
            OnForensicsInfoChanged?.Invoke(fingerprint, dna);
        #endregion
        RecordContainer.AddChild(newRecord);
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
            OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

    #region
    private void UpdateRecordActionButtons()
    {
        if (_deleteConfirmationKey != _selectedKey)
            ResetDeleteConfirmation();

        // Pirate: allow creating records from any filter input after sanitizing the entered text
        AddRecordButton.Disabled = !CanCreateRecordFromSearch();
        AddRecordButton.ToolTip = Loc.GetString("general-station-record-console-add-record"); // Pirate: add-record sanitization
        DeleteRecordButton.Disabled = !_canManageRecords || _selectedKey == null;
        DeleteRecordButton.ToolTip = _deleteConfirmationPending
            ? Loc.GetString("general-station-record-console-confirm-delete")
            : Loc.GetString("general-station-record-console-delete-record"); // Pirate: localize general console delete tooltip

        if (_deleteConfirmationPending)
        {
            if (!DeleteRecordButton.StyleClasses.Contains("ButtonColorRed"))
                DeleteRecordButton.StyleClasses.Add("ButtonColorRed");
        }
        else
        {
            DeleteRecordButton.StyleClasses.Remove("ButtonColorRed");
        }
    }

    private void CreateRecordFromSearch()
    {
        // Pirate: sanitize any current filter input into a record name and clamp it to the configured maximum
        var name = SanitizeRecordName(StationRecordsFiltersValue.Text);
        if (string.IsNullOrWhiteSpace(name))
            return;

        ClearCreateRecordValidation(); // Pirate: add-record sanitization
        ResetDeleteConfirmation();
        OnCreateRecord?.Invoke(name);
    }

    #region Pirate: add-record sanitization
    private string SanitizeRecordName(string text)
    {
        var sanitized = text.Trim();
        if (sanitized.Length > _maxLength)
            sanitized = sanitized[..(int) _maxLength];

        return sanitized;
    }

    private bool HasSelectedRecord()
    {
        foreach (var _ in RecordListing.GetSelected())
        {
            return true;
        }

        return false;
    }

    private bool CanCreateRecordFromSearch()
    {
        var name = SanitizeRecordName(StationRecordsFiltersValue.Text);
        return _canManageRecords
            && !string.IsNullOrWhiteSpace(name);
    }

    private void ClearCreateRecordValidation()
    {
        if (RecordListing.Visible)
            RecordListingStatus.Visible = false;
    }
    #endregion

    private void ResetDeleteConfirmation()
    {
        _deleteConfirmationPending = false;
        _deleteConfirmationKey = null;
    }
    #endregion
}
